from enum import Enum


class WorkflowState(str, Enum):
    SESSION_STARTED = "SESSION_STARTED"
    USER_REGISTERED = "USER_REGISTERED"
    PRODUCT_SELECTED = "PRODUCT_SELECTED"
    HUMAN_REQUIREMENTS_DRAFT = "HUMAN_REQUIREMENTS_DRAFT"
    HUMAN_REQUIREMENTS_CONFIRMED = "HUMAN_REQUIREMENTS_CONFIRMED"
    TECHNICAL_VALIDATION = "TECHNICAL_VALIDATION"
    TECH_SPEC_FINALIZED = "TECH_SPEC_FINALIZED"
    PRICING_AND_STOCK_EVALUATION = "PRICING_AND_STOCK_EVALUATION"
    ORDER_REVIEW = "ORDER_REVIEW"
    ORDER_CONFIRMED = "ORDER_CONFIRMED"


class ProductCategory(str, Enum):
    STORAGE_UNIT = "STORAGE_UNIT"
    KITCHEN_MODULE = "KITCHEN_MODULE"
    ENTERTAINMENT_UNIT = "ENTERTAINMENT_UNIT"
    SEATING = "SEATING"
    BEDDING = "BEDDING"


class FieldValueType(str, Enum):
    STRING = "STRING"
    NUMBER = "NUMBER"
    BOOLEAN = "BOOLEAN"
    ENUM = "ENUM"
